spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/immaru
    username: immaru
    password: immaru
  flyway:
    create-schemas: true
    schemas: immaru
    default-schema: immaru
  servlet.multipart:
    max-file-size: 100GB
    max-request-size: 100GB

immaru:
  library:
    path: /data/immaru-dev/files

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger