spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/immaru-dev?currentSchema=immaru
    username: immaru-dev
    password: immaru-dev
immaru:
  library:
    path: ${java.io.tmpdir}/data/immaru-dev

logging:
  level:
    Exposed: DEBUG