version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 10
    directory: "/"
    commit-message:
      prefix: "build(deps)"
    groups:
      all|minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      all|major:
        update-types:
          - "major"
        patterns:
          - "*"
    exclude-paths:
      - legacy/**
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps)"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
