spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/immaru_dev?currentSchema=immaru
    username: immaru_dev
    password: immaru_dev
immaru:
  library:
    path: ${java.io.tmpdir}/data/immaru-dev

logging:
  level:
    Exposed: DEBUG